/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: 'var(--destructive)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
        // Palette officielle AllnessPay — via CSS variables
        allness: {
          dark: 'var(--brand-sidebar)',
          darker: '#0A2226',
          green: 'var(--brand-green)',
          greenHover: '#00563A',
          orange: 'var(--brand-orange)',
          orangeHover: '#B3771F',
          red: 'var(--brand-red)',
          gray: '#6B7280',
          border: 'var(--brand-border)',
        },
        brand: {
          bg: 'var(--brand-bg)',
          sidebar: 'var(--brand-sidebar)',
          header: 'var(--brand-header)',
          card: 'var(--brand-card)',
          'card-main': 'var(--brand-card-main)',
          border: 'var(--brand-border)',
          text: 'var(--brand-text)',
          'text-secondary': 'var(--brand-text-secondary)',
          'text-disabled': 'var(--brand-text-disabled)',
          orange: 'var(--brand-orange)',
          green: 'var(--brand-green)',
          'green-light': 'var(--brand-green-light)',
          red: 'var(--brand-red)',
          blue: 'var(--brand-blue)',
          'bg-green-light': 'var(--brand-bg-green-light)',
          'bg-red-light': 'var(--brand-bg-red-light)',
          'bg-gold-light': 'var(--brand-bg-gold-light)',
          input: 'var(--brand-input)',
          'input-border': 'var(--brand-input-border)',
          hover: 'var(--brand-hover)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['Geist Variable', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
